---
- name: overlay
  hosts: freebsd
  become: yes
  vars:
    jail_dist_download: false
    before_jail_installation: false
    ocserv: false
    jails:
      - overlay

  tasks:
    - include_vars:
        file: ipam.yml
        name: ipam

    - include: tunnel/playbook.yml
      tags: tunnel
      when:
        - before_jail_installation

    - include: bgp/playbook.yml
      tags: bird
      when:
        - before_jail_installation

    - include: jail/playbook.yml
      tags: jails
      when:
        - before_jail_installation

    # At this moment we need manual actions here
    - include: jail/ocserv.yml
      tags: jails
      when: ocserv